### ISSUE TITLE
Drush hangs when excuting

### ISSUE THREAD

**Issue by wvdakker** [tusharvjoshi/netbeans-php-drupal#21]
Netbeans 7.01
Drush 4.5
Drupal 7.12
Nb 2.0.10

When I run Drush from Netbeans I get: 
Execute: /usr/share/drush/drush -r /usr/share/drupal7 --include=/home/xxxx/.netbeans/7.0/NBDrush --uri localhost -y cc all

Then nothing happens.
Listing the running processes dont show Drush is running.
If I cancel drush (by hitting the X) it shows ... 
Aborting ...
Executing complete in 20 seconds.
I can also let it run 100 seconds. Nothing happens.

If I use the same command in the CLI then it works ok.

Any thoughts?

**Comment by lanceh1412** [comment]
Same problem. Ubuntu 14.04, netbeans 8.0.2, drupal 7.39, drush 6.2.0

**Comment by agilis1** [comment]
Same problem here as well. CentOS 6.7, Netbeans 8.1, drush 6.7.0.

Checking the NetBeans IDE log displays the error associated with the hanging:
`Cannot run program "--root="/home/agilis/PublicHtml/DrupalTestBase/webroot/sites/all/modules/rowanonline_test"" (in directory "/usr/bin"): error=2, No such file or directory`

**Comment by silkentrance** [comment]
With drush 8.1 this works as expected. Perhaps you should upgrade your drush?

**Comment by wvdakker** [comment]
Solved.
