### ISSUE TITLE
Announcement: nbddapigen is now available

### ISSUE THREAD

**Issue by silkentrance** [tusharvjoshi/netbeans-php-drupal#39]
As a first release I present you nbddapigen, a simple api generator for NBDrupalDevel.

See https://github.com/coldrye-php/nbddapigen and https://github.com/coldrye-php/nbddapigen/releases.

For Linux there exist both deb and rpm packages. See the package source for more information on what is being installed and where.

On Windows you will have to install from the provided tar.gz release. If you have any suggestions/provable solutions on how to provide a package that can be installed on Windows, feel free to file an issue https://github.com/coldrye-php/nbddapigen/issues.

Please note that this is a WIP, yet it works as expected and will generate the API documentation just fine.

Perhaps this might also be a provable solution for #38.

**Comment by silkentrance** [comment]
@HollyIT how about this one. would that solve your problems of having to maintain the api docs/code templates manually?

**Comment by silkentrance** [comment]
@uberhacker no special casing for windows users here. if you need windows integration, file an issue against the aforementioned project and provide a PR.

**Comment by silkentrance** [comment]
@tusharvjoshi I very much like to make this part of the NDDT and thus part of the Java part and not as a third party tool that you need to invoke on the command line.

However, current state of the PHP IDE integration is that most frameworks/APIs are considered internal and one may not access the AST builder directly in order to be able to implement such a tool.

Care for joining me in lobbying the team responsible for the PHP IDE integration part so that they rework their internal architecture and make useful APIs such as the AST and AST builder a public component?

See https://netbeans.org/bugzilla/show_bug.cgi?id=268539.

**Comment by tusharjoshi** [comment]
@silkentrance I will need some more time to go through your project and understand what it is and why it is needed, looks like an important part of php/drupal tools.

To start with I have voted for your issue in NetBeans bugzilla and added myself as CC to that issue so we can track that issue together.

I am with you for any enhancement requests needed from NetBeans side.

**Comment by silkentrance** [comment]
Since I have moved to jetbrains/phpstorm, I have no longer a need for that.
Would you care to take over?

**Comment by tusharjoshi** [comment]
Sure @silkentrance as I have taken netbeans-php-drupal project, I would also help taking over your project.  My progress may be slow for initial days but I will try to merge these projects eventually to make them one code base, as you have envisioned.

**Comment by silkentrance** [comment]
@tusharvjoshi I have just opened a transfer request for that project.
